### ISSUE TITLE
Linux Install? No setup.py.

### ISSUE THREAD

**Issue by deleuzer** [julianandrews/flopferret#7]
Hi Julian,
I can't figure out how to install flopferret using linux.  I do not see any setup.py in any of the downloads or in the source code.  Can you give any advice?

**Comment by deleuzer** [comment]
More info.  I have now installed pyeval7, which I now understand is where the setup.py exists.  However, when I try to run the program this is what I get:

0 ross@virilio:~/packages/flopferret-0.1-alpha$ python main_window.py
Traceback (most recent call last):
  File "main_window.py", line 20, in <module>
    import board_texture
  File "/home/ross/packages/flopferret-0.1-alpha/board_texture.py", line 16, in <module>
    import pokereval
ImportError: No module named pokereval
1 ross@virilio:~/packages/flopferret-0.1-alpha$ 

I assumed that pyeval7 would install the pokereval module.  Any thoughts?  I'm running Debian Stretch.

**Comment by JulianAndrews** [comment]
The issue here is that I switched to pyeval7 after the 0.1 release (the old version used the pokereval library). You can either install the pokereval library (I think `python-pypoker-eval` is the Debian package), or you can use a more recent commit of flopferret. Probably the first is the better option here, since I'm not totally confident that the current head of master is clean of bugs, but you can try either.

Also, you'll want to run the program with `python __main__.py` or from a higher directory, just `python flopferret`

I intend to tidy this all up and make a reasonably stable release that uses pyeval7 (which performs better and sets me up to make a fully-fledged equity calculator on top of the range evaluator), but I've been surprisingly busy the past few months, and flopferret hasn't been my highest priority! I actually was just thinking to try to do that this weekend, so I'll let you know if I get something sable and reasonable in place.

**Comment by deleuzer** [comment]
Oh interesting.  I should have looked for the python-pypoker-eval package, but I assumed it was some sort of custom thing.  Anyway, that solved the problem, and I look forward to your further progress with this.  Seems great so far!!!

**Comment by noeldum** [comment]
For those planning to install this on Ubuntu bionic you will need pypoker-eval from here
https://github.com/minmax/pypoker-eval
(pypoker-eval is no longer part of the repo unfortunately)

And libpoker-eval from here
https://ubuntu.pkgs.org/16.04/ubuntu-universe-amd64/libpoker-eval_138.0-1_amd64.deb.html

**Comment by julianandrews** [comment]
After all this time, I finally got around to packaging this a little better. It should be possible to just install via pip (instructions in the README).
